# Generated by Django 4.0 on 2022-01-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='Student_Profile_Photo',
            field=models.ImageField(blank=True, upload_to='Profile_Pics'),
        ),
    ]
