# Generated by Django 4.0 on 2022-01-29 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Dashboard', '0002_alter_student_profile_student_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='Display_Name',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note_Title', models.CharField(max_length=256)),
                ('Note_Description', models.TextField(max_length=4096)),
                ('Note_Document', models.FileField(blank=True, upload_to='Notes_Documents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
