# Generated by Django 4.0 on 2022-01-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_notes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_profile',
            options={'verbose_name': 'Student_Profiles', 'verbose_name_plural': 'Student_Profiles'},
        ),
    ]
