# Generated by Django 4.0 on 2022-01-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_todo_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='Homework_Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='Homework_Due',
            field=models.DateTimeField(blank=True),
        ),
    ]
